---
kind: common.Repository
spec:
  licenses: []
  conformGPGSignatureCheck: false
---
kind: golang.Generate
spec:
    versionPackagePath: internal/version
---
kind: service.CodeCov
spec:
  enabled: false
---
kind: common.Image
spec:
  entrypointArgs:
    - vmtoolsd
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
