apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: talos-vmtoolsd
  name: talos-vmtoolsd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: talos-vmtoolsd
  template:
    metadata:
      labels:
        app: talos-vmtoolsd
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      priorityClassName: system-node-critical
      restartPolicy: Always
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - image: ghcr.io/siderolabs/talos-vmtoolsd:latest
          imagePullPolicy: Always
          name: talos-vmtoolsd
          volumeMounts:
            - name: config
              mountPath: /etc/talos-vmtoolsd
              readOnly: true
          env:
            - name: GRPC_ENFORCE_ALPN_ENABLED
              value: "false"
            - name: VMTOOLSD_TALOS_CONFIG
              value: /etc/talos-vmtoolsd/talosconfig
            - name: VMTOOLSD_TALOS_NODE
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              memory: 8Mi
            limits:
              memory: 64Mi
              cpu: 500m
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              drop:
                - all
              add:
                - SYS_RAWIO # Overrideenvironments/equinix/hieradata/nodes/Linux/vpn01-am3-mcl.yaml with VMTOOLSD_SKIP_VMWARE_DETECTION
      securityContext:
        fsGroup: 0
      volumes:
        - name: config
          secret:
            secretName: talos-vmtoolsd-config
            defaultMode: 0400
